### PR TITLE
Docker-compose version of dnscrypt-server

### PR DESCRIPTION
**Pull request by nyvanga**
Can't claim that I have completely understood your setup, but I just saw your docker commands and thought hey they would fit perfect in a docker-compose.
So I haven't checked the complete setup, but this one runs and spits out something that looks similar to what your setup.sh did. And it seems you end up with the same container running.
Hope you can use the input...
NOTE! I had some trouble with the network "piholed_static-network" so it is defined in the docker-compose file, and might conflict with already created networks.

### CODE REVIEW

**Comment by nyvanga** [comment]
I think I got the part about the network now. And changed the docker-compose accordingly.

**Comment by larssb** [comment]
This is wonderful @nyvanga ... thank you a very much. And you are the lucky pusher of the first pull-request on this project. Maybe we should've mobbed it out 😉 .... But great stuff. I'll give it a look now.

**Review by larssb — CHANGES_REQUESTED** [review]
According to [Eliminate what's superfluous](https://github.com/jedisct1/dnscrypt-server-docker/commit/f39cbaa192f712a1bbc8e539c40d0e2d008f1632) ... we can:

- remove the use of `ulimits`
- also network_mode = host is not needed ... nice! As this is a potential security issue. However in the static-network context this is not a worry. So this is just info

So throw out the ulimit and of we go. And I'll use your docker-compose.yml file for the dnscrypt-server in the unit-deployment setup as well. And for one that does not use a static-network

**Comment by nyvanga** [comment]
I just picked up the ulimits from the command line in the original setup.sh script. Didn't really know if it was needed. But no worries. They are gone!

**Review by larssb — APPROVED** [review]
Perfect stuff 👍

**Comment by larssb** [comment]
Yes I happened to update the `dnscrypt-server` `setup.sh` file earlier today. After I, last night, found out that `ulimit` and `host network mode` should no longer be used.

Thank you!

**Pull request merged**
